class ShapeTypes(object):

    CIRCLE = "circle"
    QUARTERCIRCLE = "quarter_circle"
    HALFCIRCLE = "semicircle"
    CROSS = "cross"
    TRIANGLE = "triangle"
    SQUARE = "square"
    RECTANGLE = "rectangle"
    TRAPEZOID = "trapezoid"
    PENTAGON = "pentagon"
    HEXAGON = "hexagon"
    HEPTAGON = "heptagon"
    OCTAGON = "octagon"
    STAR = "star"
